server:
  port: 8091

spring:
  application:
    name: stream-kafka-consumer
  cloud:
    stream:
      kafka:
          binder:
            brokers: localhost:9092
            zkNodes: localhost:2182
#            auto-add-partitions: true
#            auto-create-topics: true  #自动创建新主题
#            min-partition-count: 1
      bindings:
          input:
            destination: stream-kafka-qian
            content-type: application/json
            group: kafka-qian  #有分组，代表持久化