server:
  port: 8091

spring:
  application:
    name: stream-kafka-consumer
  cloud:
    stream:
      kafka:
        # 来自KafkaBinderConfigurationProperties
        binder:
          brokers: localhost:9092
          zkNodes: localhost:2181       #可配置zookeeper集群用逗号分隔
#          auto-add-partitions: true
#          auto-create-topics: true  #自动创建新主题
#          min-partition-count: 1
      # 属性来自BindingProperties
      bindings:
      # 配置多个输入通道 ，与@StreamListener注解中的value一致，是绑定的渠道名
        input:
          # 绑定的kafka topic
          destination: stream-kafka-qian
          content-type: application/json
          # 消费组
          group: kafka-qian_input  # 有分组，代表持久化
        my_input:
          destination: stream-kafka-qian-my
          content-type: application/json
          group: kafka-qian  # 有分组，代表持久化