server:
  port: 8090

spring:
  application:
    name: stream-kafka-provider
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zkNodes: localhost:2181
#           auto-add-partitions: true
#           auto-create-topics: true  #自动创建新主题
#           min-partition-count: 1
      bindings:
      # 配置多个输出通道,与@StreamListener注解中的value一致，是绑定的渠道名
        output:
          destination: stream-kafka-qian
          contentType: application/json
        my_output:
          destination: stream-kafka-qian-my
          contentType: application/json